version: '3'
services:
  service:
    container_name: fullstack-lms-go
    working_dir: /build
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - app-build-data:/build

  postgres:
    image: postgres:12
    container_name: fullstack-lms-go-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    container_name: fullstack-lms-go-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=fullstack-lms-go-redis
      - REDIS_DB_NUMBER=0

volumes:
  app-build-data:
  db-data: